theme: minima  # You can change this to your preferred theme
title: My Awesome Site
description: A brief description of my site
url: https://myawesomesite.com
baseurl: "" # the subpath of your site, e.g. /blog

navbar:
  - title: Home
    url: /
  - title: About
    url: /Exp/
  - title: Projects
    url: /projects/
