theme: minima  # You can change this to your preferred theme
title: Arshan Khan  
navbar:
  - title: Home
    url: /Home/
  - title: Research
    url: /Research/
  - title: Publications
    url: /Publications/
- title: Experience
    url: /Exp/
   - title: Awards
    url: /Awards/
    - title: Contact
    url: /Contact/
