theme: minima  # You can change this to your preferred theme
title: Arshan Khan  

navbar:
  - title: Home
    url: /Home/
  - title: Research
    url: /Research/
  - title: Publications
    url: /Publications/
  - title: Awards
    url: /Awards/
  - title: Experience
    url: /Exp/
  - title: Contact
    url: /Contact/
